#------------------------------------------------------------------------------ 
# written by: Miguel Afonso
#             https://www.linkedin.com/in/mmafonso/
#
# date: Aug-2021
#
# usage: setup SSL certs for EKS load balancer worker node instances.
#------------------------------------------------------------------------------ 
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: no-reply@turnthebus.org
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          route53:
            region: ap-south-1
            hostedZoneID: Z0540686GYG3QL4XM567

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-crt
spec:
  secretName: wild-openedx-prod-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: app.turnthebus.org
  dnsNames:
    - "*.app.turnthebus.org"
