#------------------------------------------------------------------------------
# written by: Lawrence McDaniel
#             https://lawrencemcdaniel.com/
#
# date: Feb-2022
#
# usage: Dumps mysql and mongo. stores the completed backups in AWS S3
#------------------------------------------------------------------------------
#